### ISSUE TITLE
"Before Starting" section and git clone command, notebooks not working

### ISSUE THREAD

**Issue by fredgis** [solliancenet/azure-synapse-wwi-lab#6]
Hi Team,
I hope you're going well.
I'm a cloud solution architect at Microsoft France and I work on your workshop around Synapse. I create a fresh environment today following each step beginning by the "Before Starting section". 

It seems that when I clone the Github repository those cloned notebooks are not up to date, I just follow the "Before Starting section", those are not up to date.

The cloned repository is the master branch and the Product Recommandation Workbook is not up to date and not working.
For example the second cell is (with my suffix ocpsyn)

%%pyspark
customer_data = spark.read.load('abfss://machine-learning@asaexpdatalakeocpsyn.dfs.core.windows.net/customer-sales-latest.csv'
    ,format='csv'
    ,header=True)
customer_data.show(10)

And the last cell of this notebook is number 12.

When I check the repository I find the branch 2735c6873d and the associated notebooks works fine, the second cell of the recommendation workbook is

%%spark
val df = spark.read.sqlanalytics("SQLPool01.dbo.Customer_SalesLatest") 
  df.head(10)
  //Create a Temp view for using the dataframe from Scala to Python
  df.createOrReplaceTempView ("df")

I check the git clone on the azure shell and it seems to have the first version of the notebook, those which do not work.

Thanks for your feedback,
Frederic

**Comment by daronyondem** [comment]
Hi Fredric,

The notebook has changed. Can you try running the pipeline called `ML Product Recommendation` and see if the notebook succeeds? The pipeline will make sure the required files by the notebook are generated. 

Let me know your findings.

Thanks

**Comment by fredgis** [comment]
Hi Daron

Yes this pipeline is working well.
Could you update the HOL-step-by-step.md in order to put this new approach in place of the Task 3 in the Exercice 3 ? It's still focus on the old notebook and not the global pipeline.

Is it the same with the task 4 autoML ? Focus on a new pipeline ?

Thanks for all
Frederic

**Comment by daronyondem** [comment]
Yes. This repo is a work in progress. Sorry about the inconvenience. The `ML Department Visit Predictions` is the right one to get things prepared for the AutoML Notebook.

**Comment by daronyondem** [comment]
Hi, @fredgis I'm back with an update. If you run the provisioning again you should not have any problems running the notebooks stand-alone anymore. With that said, in your situation, after at least running the pipelines once, you can go back and run the notebooks successfully. I hope this helps. Thanks for reporting the issue ;)

**Comment by fredgis** [comment]
Hi Daron,
Thanks a lot !
