### ISSUE TITLE
./01-environment-setup.ps1 not working

### ISSUE THREAD

**Issue by fredgis** [solliancenet/azure-synapse-wwi-lab#7]
Hi @daronyondem 

I completely clean my environment and try to setup another one, with a first approach of git pull, and finally a new git clone, both have the same failed result on setup automation.

Can you help me on this,
Thanks

Enter the SQL Administrator password you used in the deployment: *********************
InvalidOperation: /home/frederic/synapse-wwiv2/artifacts/environment-setup/automation/01-environment-setup.ps1:84
Line |
  84 |  $uniqueId = (Get-AzResource -ResourceGroupName $resourceGroupName -Re …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.

Assign Ownership to Proctors on Synapse Workspace
Invoke-RestMethod: /home/frederic/synapse-wwiv2/artifacts/environment-setup/solliance-synapse-automation/solliance-synapse-automation.psm1:1462
Line |
1462 |  …   $result = Invoke-RestMethod  -Uri $uri -Method $method -Body $body  …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Name or service not known

Invoke-RestMethod: /home/frederic/synapse-wwiv2/artifacts/environment-setup/solliance-synapse-automation/solliance-synapse-automation.psm1:1462
Line |
1462 |  …   $result = Invoke-RestMethod  -Uri $uri -Method $method -Body $body  …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Name or service not known

Invoke-RestMethod: /home/frederic/synapse-wwiv2/artifacts/environment-setup/solliance-synapse-automation/solliance-synapse-automation.psm1:1462
Line |
1462 |  …   $result = Invoke-RestMethod  -Uri $uri -Method $method -Body $body  …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Name or service not known

New-AzRoleAssignment: /home/frederic/synapse-wwiv2/artifacts/environment-setup/automation/01-environment-setup.ps1:121
Line |
 121 |  New-AzRoleAssignment -Objectid $id -RoleDefinitionName "Storage Blob  …
     |                                 ~~~
     | Cannot validate argument on parameter 'ObjectId'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.

**Comment by daronyondem** [comment]
Are you sure you ran az login before?

**Comment by fredgis** [comment]
@daronyondem yes just retry, az login ok, I select the subscription and after I enter the SQL password all fail

**Comment by daronyondem** [comment]
You might be experiencing a glitch in the cloud shell. I suggest deleting the storage account used by cloud shell and try starting from scratch.

**Comment by fredgis** [comment]
@daronyondem ok the deployment succeeded when I completely remove storage account and all old deployed ressources (completely drop the synapse workspace previously created) .

But I think there's still a problem.
The Notebook deployed only have 12 cells (1 Products Recommendations). 

When you complete the task "Task 3: Using Notebooks to Run Machine Learning Experiments" of the exercice 3 you ask to add this code after the cell 25.

%%pyspark
output = recommend_products(user_id=1533, num=7)
output

But this doesn't work because 

NameError : name 'recommend_products' is not defined
Traceback (most recent call last):
NameError: name 'recommend_products' is not defined

Could you fix this and or deploy the good Notebook in the synapse workspace or adapt the approach ?

Thanks

**Comment by daronyondem** [comment]
Good to hear @fredgis Sometimes Cloud Shell does not behave. If you are sure you did everything right but getting weird errors when you run the automation script it is a good idea to delete the storage to reset cloud shell.

I will give you another update about the notebook. 👍

**Comment by fredgis** [comment]
Hi @daronyondem any update on this issue ?
Keep me inform, I will drive a partner session based on this content, it's why I'm very aware of it :)

Thanks for your work
Fred

**Comment by fredgis** [comment]
Hello @daronyondem , any news on your side ? :)
Thanks
Fred

**Comment by daronyondem** [comment]
Hi @fredgis 

We moved this repo to https://github.com/microsoft/Azure-Analytics-and-AI-Engagement Please have a look at the updates there and feel free to submit an issue if the error still persists.

Thanks.
