### ISSUE TITLE
Choose 30 billion records, I get this error that keeps repeating

### ISSUE THREAD

**Issue by timahenning** [solliancenet/azure-synapse-wwi-lab#9]
On another note, I’m setting up the lab for https://github.com/solliancenet/azure-synapse-wwi-lab

When I run ./01-environment-setup.ps1 And choose 30 billion records, I get this error that keeps repeating:

InvalidOperation: /home/james/synapse-wwi/artifacts/environment-setup/solliance-synapse-automation/solliance-synapse-automation.psm1:968
Line |
968 |      $ie.visible = $true;
     |      ~~~~~~~~~~~~~~~~~~~
     | The property 'visible' cannot be found on this object. Verify that the property exists and can be set.

InvalidOperation: /home/james/synapse-wwi/artifacts/environment-setup/solliance-synapse-automation/solliance-synapse-automation.psm1:970
Line |
970 |      $ie.Navigate($url)
     |      ~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.

InvalidOperation: /home/james/synapse-wwi/artifacts/environment-setup/solliance-synapse-automation/solliance-synapse-automation.psm1:971
Line |
971 |      $ie.visible = $false;
     |      ~~~~~~~~~~~~~~~~~~~~
     | The property 'visible' cannot be found on this object. Verify that the property exists and can be set.

InvalidOperation: /home/james/synapse-wwi/artifacts/environment-setup/solliance-synapse-automation/solliance-synapse-automation.psm1:978
Line |
978 |      $inputs = $ie.Document.body.getElementsByTagName("input");
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.

InvalidOperation: /home/james/synapse-wwi/artifacts/environment-setup/solliance-synapse-automation/solliance-synapse-automation.psm1:984
Line |
984 |      $buttons = $ie.Document.body.getElementsByTagName("button");
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.

InvalidOperation: /home/james/synapse-wwi/artifacts/environment-setup/solliance-synapse-automation/solliance-synapse-automation.psm1:987
Line |
987 |      $msgInput.value = $message.replace("`r","\r").replace("`n","\n");
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The property 'value' cannot be found on this object. Verify that the property exists and can be set.

InvalidOperation: /home/james/synapse-wwi/artifacts/environment-setup/solliance-synapse-automation/solliance-synapse-automation.psm1:988
Line |
988 |      $secretInput.value = $secret;
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The property 'value' cannot be found on this object. Verify that the property exists and can be set.

InvalidOperation: /home/james/synapse-wwi/artifacts/environment-setup/solliance-synapse-automation/solliance-synapse-automation.psm1:989
Line |
989 |      $btnGo.click();
     |      ~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.

InvalidOperation: /home/james/synapse-wwi/artifacts/environment-setup/solliance-synapse-automation/solliance-synapse-automation.psm1:992
Line |
992 |      $ie.quit();
     |      ~~~~~~~~~~
     | You cannot call a method on a null-valued expression.

Error getting CSRF
Invoke-WebRequest: /home/james/synapse-wwi/artifacts/environment-setup/solliance-synapse-automation/solliance-synapse-automation.psm1:928
Line |
928 |  … rawResult = Invoke-WebRequest -Uri $uri -Method POST -Body $SQLQuery  …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The X-CSRF-Signature header could not be validated.

ConvertFrom-Json: /home/james/synapse-wwi/artifacts/environment-setup/solliance-synapse-automation/solliance-synapse-automation.psm1:931
Line |
931 |      $result = ConvertFrom-Json $rawResult.Content
     |                                 ~~~~~~~~~~~~~~~~~~
     | Cannot bind argument to parameter 'InputObject' because it is null.

James Serra

**Comment by daronyondem** [comment]
This repository is not used anymore. Repository content is moved to https://github.com/microsoft/Azure-Analytics-and-AI-Engagement. Thanks.
